@SnpWebApp_HostAddress = https://localhost:7188

POST {{SnpWebApp_HostAddress}}/api/insertdaily
Content-Type: application/json
x-api-key: {APIKEY}

{
  "points": 123.4,
  "change": 2.22,
  "move": 0.25,
  "date": "2025-12-25"
}

###

PUT {{SnpWebApp_HostAddress}}/updatedaily
Content-Type: application/json

{
  "points": 2222.4,
  "change": 800.22,
  "move": 3.75,
  "date": "2025-11-17"
}

###

DELETE {{SnpWebApp_HostAddress}}/deletestocks
Content-Type: application/json

[
    "MMM", "AAPL"
]

###

POST {{SnpWebApp_HostAddress}}/api/replacesnp
Content-Type: application/json
x-api-key: {apikey}


  [{"exchangeUrl": "www.nasdaq.com/MMM", "symbol": "MMM", "security": "3M", "sector": "Tech", "subIndustry": "Sub Tech", "hqLocation": "wyoming", "dateAdded": "2011-02-15", "CIK": 1548, "founded": "2002 (1999)"}, {"exchangeUrl": "www.nasdaq.com/NVDA", "symbol": "NVDA", "security": "Nvidia", "sector": "Tech", "subIndustry": "Sub Tech", "hqLocation": "new jersey", "dateAdded": "2000-02-15", "CIK": 1548, "founded": "2002 (1999)"}]

###
